In [20]:
%matplotlib inline

import pandas as pd

# these will be useful later
import numpy  as np
from matplotlib import pyplot as plt

In [21]:
#Homicide Rates in 2013
crime=pd.read_csv("mun.csv", index_col = "id", parse_dates = ["id"], encoding='iso-8859-1')
crime=crime.drop('SUBTIPO', axis=1)

In [22]:
hom13= crime[(crime['MODALIDAD']=='HOMICIDIOS') & (crime['TIPO'] == 'DOLOSOS' )]
hom13= hom13.groupby([hom13.index,'year','ENTIDAD', 'MUNICIPIO']).sum().reset_index()
hom13=hom13.set_index(['id'])
hom13=hom13[hom13.year == 2013]
hom13=hom13.rename(columns = {'total':'homicidios'})

In [23]:
pop=pd.read_csv("pop.csv", index_col = "id", parse_dates = ["id"], encoding='iso-8859-1')
pop=pop.drop('hom', axis=1)
pop=pop.drop('muj', axis=1)

In [41]:
tot13 = pd.concat([hom13, pop], axis=1)
tot13= tot13.drop('nom', axis=1)
tot13['hom_rate'] = (tot13['homicidios']/tot13['pop'])*100000
tot13 = tot13.drop("MUNICIPIO", axis=1)
tot13 = tot13.rename(columns = {'hom_rate': 'Homicide Rate in 2013',
                               'homicidios':'Homicides in 2013'})
tot13.head(10)

,year,ENTIDAD,Homicides in 2013,pop,Homicide Rate in 2013
id,,,,,
1001,2013.0,AGUASCALIENTES,19.0,797010.0,2.383910
1002,2013.0,AGUASCALIENTES,5.0,45492.0,10.990943
1003,2013.0,AGUASCALIENTES,0.0,54136.0,0.000000
1004,2013.0,AGUASCALIENTES,0.0,15042.0,0.000000
1005,2013.0,AGUASCALIENTES,7.0,99590.0,7.028818
1006,2013.0,AGUASCALIENTES,1.0,41862.0,2.388801
1007,2013.0,AGUASCALIENTES,2.0,49156.0,4.068679
1008,2013.0,AGUASCALIENTES,0.0,8443.0,0.000000
1009,2013.0,AGUASCALIENTES,0.0,19668.0,0.000000
1010,2013.0,AGUASCALIENTES,1.0,18828.0,5.311239

In [42]:
#Homicide Rates in 2014
crime=pd.read_csv("mun.csv", index_col = "id", parse_dates = ["id"], encoding='iso-8859-1')
crime=crime.drop('SUBTIPO', axis=1)
hom14= crime[(crime['MODALIDAD']=='HOMICIDIOS') & (crime['TIPO'] == 'DOLOSOS' )]
hom14= hom14.groupby([hom14.index,'year','ENTIDAD', 'MUNICIPIO']).sum().reset_index()
hom14=hom14.set_index(['id'])
hom14=hom14[hom14.year == 2014]
hom14=hom14.rename(columns = {'total':'homicidios'})
pop=pd.read_csv("pop.csv", index_col = "id", parse_dates = ["id"], encoding='iso-8859-1')
pop=pop.drop('hom', axis=1)
pop=pop.drop('muj', axis=1)
tot14 = pd.concat([hom14, pop], axis=1)
tot14= tot14.drop('nom', axis=1)
tot14['hom_rate'] = (tot14['homicidios']/tot14['pop'])*100000
tot14 = tot14.rename(columns = {'hom_rate': 'Homicide Rate in 2014',
                               'homicidios':'Homicides in 2014'})

tot14.head(10)

,year,ENTIDAD,MUNICIPIO,Homicides in 2014,pop,Homicide Rate in 2014
id,,,,,,
1001,2014.0,AGUASCALIENTES,AGUASCALIENTES,31.0,797010.0,3.889537
1002,2014.0,AGUASCALIENTES,ASIENTOS,0.0,45492.0,0.000000
1003,2014.0,AGUASCALIENTES,CALVILLO,2.0,54136.0,3.694399
1004,2014.0,AGUASCALIENTES,COSIO,0.0,15042.0,0.000000
1005,2014.0,AGUASCALIENTES,JESUS MARIA,6.0,99590.0,6.024701
1006,2014.0,AGUASCALIENTES,PABELLON DE ARTEAGA,0.0,41862.0,0.000000
1007,2014.0,AGUASCALIENTES,RINCON DE ROMOS,1.0,49156.0,2.034340
1008,2014.0,AGUASCALIENTES,SAN JOSE DE GRACIA,0.0,8443.0,0.000000
1009,2014.0,AGUASCALIENTES,TEPEZALA,0.0,19668.0,0.000000
1010,2014.0,AGUASCALIENTES,EL LLANO,1.0,18828.0,5.311239

In [27]:
#3x1 Projects Granted in 2013
x31_13 = pd.read_csv("3x1_2013utf8.csv", index_col = "id", usecols= {"id","year", "suma"}, 
                     parse_dates = ["id"])
x31_13 = x31_13.groupby([x31_13.index,'year']).sum()
x31_13 = x31_13.rename(columns = {'suma': '3x1 Projects Granted in 2013'})
x31_13 = x31_13.reset_index()
x31_13 = x31_13.set_index(['id'])
x31_13.head(10)

      year  3x1 Projects Granted in 2013
id
1001  2013                             6
1002  2013                             2
1003  2013                            17
1004  2013                             2
1006  2013                             1
1007  2013                             2
1008  2013                             4
1009  2013                             1
2001  2013                             1
2004  2013                            17

In [44]:
#3x1 Projects Granted in 2014
x31_14 = pd.read_csv("3x1_2014utf8.csv", index_col = "id", usecols= {"id","year", "suma"}, 
                     parse_dates = ["id"])
x31_14 = x31_14.groupby([x31_14.index,'year']).sum()
x31_14 = x31_14.rename(columns = {'suma': '3x1 Projects Granted in 2014'})
x31_14 = x31_14.reset_index()
x31_14 = x31_14.set_index(['id'])
x31_14.head(10)

      year  3x1 Projects Granted in 2014
id
1001  2014                             6
1002  2014                             9
1003  2014                            10
1004  2014                             5
1005  2014                             2
1006  2014                             1
1007  2014                             3
1008  2014                             3
1009  2014                             4
1011  2014                             1

In [45]:
#Merging homicide rates and 3x1 projects granted in 2013
hom_3x1_13 = pd.merge(tot13, x31_13, left_index=True, right_index=True, how='outer')
hom_3x1_13.head(10)

,year_x,ENTIDAD,Homicides in 2013,pop,Homicide Rate in 2013,year_y,3x1 Projects Granted in 2013
id,,,,,,,
1001,2013.0,AGUASCALIENTES,19.0,797010.0,2.383910,2013.0,6.0
1002,2013.0,AGUASCALIENTES,5.0,45492.0,10.990943,2013.0,2.0
1003,2013.0,AGUASCALIENTES,0.0,54136.0,0.000000,2013.0,17.0
1004,2013.0,AGUASCALIENTES,0.0,15042.0,0.000000,2013.0,2.0
1005,2013.0,AGUASCALIENTES,7.0,99590.0,7.028818,NaN,NaN
1006,2013.0,AGUASCALIENTES,1.0,41862.0,2.388801,2013.0,1.0
1007,2013.0,AGUASCALIENTES,2.0,49156.0,4.068679,2013.0,2.0
1008,2013.0,AGUASCALIENTES,0.0,8443.0,0.000000,2013.0,4.0
1009,2013.0,AGUASCALIENTES,0.0,19668.0,0.000000,2013.0,1.0
1010,2013.0,AGUASCALIENTES,1.0,18828.0,5.311239,NaN,NaN

In [46]:
#Merging homicide rates and 3x1 projects granted in 2014
hom_3x1_14 = pd.merge(tot14, x31_14, left_index=True, right_index=True, how='outer')
hom_3x1_14.head(10)

,year_x,ENTIDAD,MUNICIPIO,Homicides in 2014,pop,Homicide Rate in 2014,year_y,3x1 Projects Granted in 2014
id,,,,,,,,
1001,2014.0,AGUASCALIENTES,AGUASCALIENTES,31.0,797010.0,3.889537,2014.0,6.0
1002,2014.0,AGUASCALIENTES,ASIENTOS,0.0,45492.0,0.000000,2014.0,9.0
1003,2014.0,AGUASCALIENTES,CALVILLO,2.0,54136.0,3.694399,2014.0,10.0
1004,2014.0,AGUASCALIENTES,COSIO,0.0,15042.0,0.000000,2014.0,5.0
1005,2014.0,AGUASCALIENTES,JESUS MARIA,6.0,99590.0,6.024701,2014.0,2.0
1006,2014.0,AGUASCALIENTES,PABELLON DE ARTEAGA,0.0,41862.0,0.000000,2014.0,1.0
1007,2014.0,AGUASCALIENTES,RINCON DE ROMOS,1.0,49156.0,2.034340,2014.0,3.0
1008,2014.0,AGUASCALIENTES,SAN JOSE DE GRACIA,0.0,8443.0,0.000000,2014.0,3.0
1009,2014.0,AGUASCALIENTES,TEPEZALA,0.0,19668.0,0.000000,2014.0,4.0
1010,2014.0,AGUASCALIENTES,EL LLANO,1.0,18828.0,5.311239,NaN,NaN

In [48]:
#Dropping repeated columns in 2013
hom_3x1_13 = hom_3x1_13.drop('year_x', axis=1)
hom_3x1_13 = hom_3x1_13.drop('year_y', axis=1)
hom_3x1_13.head(10)

,ENTIDAD,Homicides in 2013,pop,Homicide Rate in 2013,3x1 Projects Granted in 2013
id,,,,,
1001,AGUASCALIENTES,19.0,797010.0,2.383910,6.0
1002,AGUASCALIENTES,5.0,45492.0,10.990943,2.0
1003,AGUASCALIENTES,0.0,54136.0,0.000000,17.0
1004,AGUASCALIENTES,0.0,15042.0,0.000000,2.0
1005,AGUASCALIENTES,7.0,99590.0,7.028818,NaN
1006,AGUASCALIENTES,1.0,41862.0,2.388801,1.0
1007,AGUASCALIENTES,2.0,49156.0,4.068679,2.0
1008,AGUASCALIENTES,0.0,8443.0,0.000000,4.0
1009,AGUASCALIENTES,0.0,19668.0,0.000000,1.0
1010,AGUASCALIENTES,1.0,18828.0,5.311239,NaN

In [49]:
#Dropping repeated columns in 2014
hom_3x1_14 = hom_3x1_14.drop('year_x', axis=1)
hom_3x1_14 = hom_3x1_14.drop('year_y', axis=1)
hom_3x1_14.head(10)

,ENTIDAD,MUNICIPIO,Homicides in 2014,pop,Homicide Rate in 2014,3x1 Projects Granted in 2014
id,,,,,,
1001,AGUASCALIENTES,AGUASCALIENTES,31.0,797010.0,3.889537,6.0
1002,AGUASCALIENTES,ASIENTOS,0.0,45492.0,0.000000,9.0
1003,AGUASCALIENTES,CALVILLO,2.0,54136.0,3.694399,10.0
1004,AGUASCALIENTES,COSIO,0.0,15042.0,0.000000,5.0
1005,AGUASCALIENTES,JESUS MARIA,6.0,99590.0,6.024701,2.0
1006,AGUASCALIENTES,PABELLON DE ARTEAGA,0.0,41862.0,0.000000,1.0
1007,AGUASCALIENTES,RINCON DE ROMOS,1.0,49156.0,2.034340,3.0
1008,AGUASCALIENTES,SAN JOSE DE GRACIA,0.0,8443.0,0.000000,3.0
1009,AGUASCALIENTES,TEPEZALA,0.0,19668.0,0.000000,4.0
1010,AGUASCALIENTES,EL LLANO,1.0,18828.0,5.311239,NaN

In [50]:
#Final Merge!!!!
hom_3x1_all = pd.merge(hom_3x1_13, hom_3x1_14, left_index=True, right_index=True, how='outer')
hom_3x1_all.head(10)

,ENTIDAD_x,Homicides in 2013,pop_x,Homicide Rate in 2013,3x1 Projects Granted in 2013,ENTIDAD_y,MUNICIPIO,Homicides in 2014,pop_y,Homicide Rate in 2014,3x1 Projects Granted in 2014
id,,,,,,,,,,,
1001,AGUASCALIENTES,19.0,797010.0,2.383910,6.0,AGUASCALIENTES,AGUASCALIENTES,31.0,797010.0,3.889537,6.0
1002,AGUASCALIENTES,5.0,45492.0,10.990943,2.0,AGUASCALIENTES,ASIENTOS,0.0,45492.0,0.000000,9.0
1003,AGUASCALIENTES,0.0,54136.0,0.000000,17.0,AGUASCALIENTES,CALVILLO,2.0,54136.0,3.694399,10.0
1004,AGUASCALIENTES,0.0,15042.0,0.000000,2.0,AGUASCALIENTES,COSIO,0.0,15042.0,0.000000,5.0
1005,AGUASCALIENTES,7.0,99590.0,7.028818,NaN,AGUASCALIENTES,JESUS MARIA,6.0,99590.0,6.024701,2.0
1006,AGUASCALIENTES,1.0,41862.0,2.388801,1.0,AGUASCALIENTES,PABELLON DE ARTEAGA,0.0,41862.0,0.000000,1.0
1007,AGUASCALIENTES,2.0,49156.0,4.068679,2.0,AGUASCALIENTES,RINCON DE ROMOS,1.0,49156.0,2.034340,3.0
1008,AGUASCALIENTES,0.0,8443.0,0.000000,4.0,AGUASCALIENTES,SAN JOSE DE GRACIA,0.0,8443.0,0.000000,3.0
1009,AGUASCALIENTES,0.0,19668.0,0.000000,1.0,AGUASCALIENTES,TEPEZALA,0.0,19668.0,0.000000,4.0
1010,AGUASCALIENTES,1.0,18828.0,5.311239,NaN,AGUASCALIENTES,EL LLANO,1.0,18828.0,5.311239,NaN

In [51]:
# Dropping repeated columns
hom_3x1_all = hom_3x1_all.drop('ENTIDAD_x', axis=1)
hom_3x1_all = hom_3x1_all.drop('pop_x', axis=1)
hom_3x1_all.head(10)

,Homicides in 2013,Homicide Rate in 2013,3x1 Projects Granted in 2013,ENTIDAD_y,MUNICIPIO,Homicides in 2014,pop_y,Homicide Rate in 2014,3x1 Projects Granted in 2014
id,,,,,,,,,
1001,19.0,2.383910,6.0,AGUASCALIENTES,AGUASCALIENTES,31.0,797010.0,3.889537,6.0
1002,5.0,10.990943,2.0,AGUASCALIENTES,ASIENTOS,0.0,45492.0,0.000000,9.0
1003,0.0,0.000000,17.0,AGUASCALIENTES,CALVILLO,2.0,54136.0,3.694399,10.0
1004,0.0,0.000000,2.0,AGUASCALIENTES,COSIO,0.0,15042.0,0.000000,5.0
1005,7.0,7.028818,NaN,AGUASCALIENTES,JESUS MARIA,6.0,99590.0,6.024701,2.0
1006,1.0,2.388801,1.0,AGUASCALIENTES,PABELLON DE ARTEAGA,0.0,41862.0,0.000000,1.0
1007,2.0,4.068679,2.0,AGUASCALIENTES,RINCON DE ROMOS,1.0,49156.0,2.034340,3.0
1008,0.0,0.000000,4.0,AGUASCALIENTES,SAN JOSE DE GRACIA,0.0,8443.0,0.000000,3.0
1009,0.0,0.000000,1.0,AGUASCALIENTES,TEPEZALA,0.0,19668.0,0.000000,4.0
1010,1.0,5.311239,NaN,AGUASCALIENTES,EL LLANO,1.0,18828.0,5.311239,NaN

In [52]:
hom_3x1_all.to_csv('master.csv')